find_package(alpaca @alpaca_VERSION@ REQUIRED HINTS @CMAKE_INSTALL_PREFIX@)
find_package(fmt @fmt_VERSION@ REQUIRED HINTS @CMAKE_INSTALL_PREFIX@)
find_package(scn @scn_VERSION@ REQUIRED HINTS @CMAKE_INSTALL_PREFIX@)
find_package(spdlog @spdlog_VERSION@ REQUIRED HINTS @CMAKE_INSTALL_PREFIX@)

@PACKAGE_INIT@

message(STATUS "*spark* found: @spark_VERSION@")
include("${CMAKE_CURRENT_LIST_DIR}/spark-targets.cmake")

set(SPARK_INSTALL_PREFIX @SPARK_INSTALL_PREFIX@)
set(SPARK_INSTALL_BINDIR @SPARK_INSTALL_BINDIR@)
set(SPARK_INSTALL_INCDIR @SPARK_INSTALL_INCDIR@)
